version: '3.5'

services:
  metadata_db:
    image: postgres:13-alpine
    restart: always
    hostname: metadata-db
    container_name: metadata-db
    networks:
      - private
    environment:
      - POSTGRES_DB=phaedra2
      - POSTGRES_USER=phaedra_usr
      - POSTGRES_PASSWORD=phaedra_usr
    volumes:
      - ./db/0-create-schema.sql:/opt/0-create-schema.sql
      - ./sh:/docker-entrypoint-initdb.d/
    ports:
      - 7654:5432
  metadata_service:
    image: phaedra2-metadataservice:0.0.1-SNAPSHOT
    hostname: phaedra2-metadataservice
    container_name: phaedra2-metadataservice
    networks:
      - private
      - phaedra2
    depends_on:
      - metadata_db
    environment:
      - DB_URL=jdbc:postgresql://metadata-db:5432/phaedra2?currentSchema=metadata
      - DB_USER=phaedra_usr
      - DB_PASSWORD=phaedra_usr
    ports:
      - 3002:3002
  metadata_liquibase:
    image: phaedra2-metadataservice.liquibase:0.0.1-SNAPSHOT
    hostname: phaedra2-metadataservice.liquibase
    container_name: phaedra2-metadataservice.liquibase
    networks:
      - private
      - phaedra2
    depends_on:
      - metadata_db
      - metadata_service
    environment:
      - DB_URL=jdbc:postgresql://metadata-db:5432/phaedra2?currentSchema=metadata
      - DB_USERNAME=phaedra_usr
      - DB_PASSWORD=phaedra_usr
      - DB_SCHEMA=metadata
networks:
  private:
    name: private
    external: false
  phaedra2:
    external:
      name: phaedra2