server:
  servlet:
    context-path: /phaedra/metadata-service
  port: 3002

spring:
  application:
    name: PHAEDRA-METADATA-SERVICE
  jackson:
    serialization:
      indent_output: true

eureka:
  instance:
    appname: ${spring.application.name}
  client:
    service-url:
      defaultZone: ${SERVICE_REGISTRY}